# Generated by Django 3.0.2 on 2020-04-25 04:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 4, 23, 44, 366434, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Bad', 'Bad'), ('Terrible', 'Terrible')], max_length=10),
        ),
    ]
