# Generated by Django 3.0.2 on 2020-04-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklog', '0002_auto_20200425_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
    ]
